"""empty message

Revision ID: 52b69b4bd5a5
Revises: eb2421efa44d
Create Date: 2024-07-07 17:01:02.219418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b69b4bd5a5'
down_revision = 'eb2421efa44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_session_deltas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_addition', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('start', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stop', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('characters', sa.String(length=2), nullable=False))
        batch_op.drop_index('ix_typing_session_deltas_delta')
        batch_op.create_index(batch_op.f('ix_typing_session_deltas_characters'), ['characters'], unique=False)
        batch_op.drop_column('delta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_session_deltas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delta', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_typing_session_deltas_characters'))
        batch_op.create_index('ix_typing_session_deltas_delta', ['delta'], unique=False)
        batch_op.drop_column('characters')
        batch_op.drop_column('stop')
        batch_op.drop_column('start')
        batch_op.drop_column('is_addition')

    # ### end Alembic commands ###
