"""initial commit 3

Revision ID: eb2421efa44d
Revises: 
Create Date: 2024-07-05 20:47:19.560725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2421efa44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=39), nullable=False),
    sa.Column('connection_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_ip'), ['ip'], unique=True)

    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_language_name'), ['language_name'], unique=False)

    op.create_table('text_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_section', sa.String(length=2000), nullable=False),
    sa.Column('language_id', sa.String(length=20), nullable=False),
    sa.Column('area_prominence', sa.String(length=1120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_section_area_prominence'), ['area_prominence'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_section_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_section_text_section'), ['text_section'], unique=False)

    op.create_table('typing_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('completion_status', sa.Integer(), nullable=False),
    sa.Column('completion_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['text_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('typing_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typing_session_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_typing_session_completion_time'), ['completion_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_typing_session_text_id'), ['text_id'], unique=False)

    op.create_table('typing_session_deltas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typing_session_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.String(length=2), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['typing_session_id'], ['typing_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('typing_session_deltas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typing_session_deltas_delta'), ['delta'], unique=False)
        batch_op.create_index(batch_op.f('ix_typing_session_deltas_typing_session_id'), ['typing_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typing_session_deltas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typing_session_deltas_typing_session_id'))
        batch_op.drop_index(batch_op.f('ix_typing_session_deltas_delta'))

    op.drop_table('typing_session_deltas')
    with op.batch_alter_table('typing_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typing_session_text_id'))
        batch_op.drop_index(batch_op.f('ix_typing_session_completion_time'))
        batch_op.drop_index(batch_op.f('ix_typing_session_client_id'))

    op.drop_table('typing_session')
    with op.batch_alter_table('text_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_section_text_section'))
        batch_op.drop_index(batch_op.f('ix_text_section_language_id'))
        batch_op.drop_index(batch_op.f('ix_text_section_area_prominence'))

    op.drop_table('text_section')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_language_name'))

    op.drop_table('languages')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_ip'))

    op.drop_table('client')
    # ### end Alembic commands ###
